name: Terraform Feature Queue Deployment

on:
  workflow_dispatch:
     inputs:
        working-directory:
            required: true
            type: choice
            description: terraform workflow directory
            options:
            - "network/shared"
            - "network/spoke"
            - "platform/spoke"
        stage:
            type: choice
            description: Target stage to test against (used by deploy-platform only)
            required: true
            options:
            - "latest"
            - "test"
            - "beta"
            - "prod"
            - "parvati"
        account:
            type: string
            description: Choose any of the known account for stage latest/test 122403041129, beta/prod 794236216820, parvati 331043233042
            required: true
        region:
            type: choice
            description: Choose ap-south-1 for parvati, rest are eu-west-1 region
            required: true
            options:
            - us-east-1
            - eu-west-1
            - ap-south-1
          
jobs:
    deploy-matrix:
      strategy:
        matrix:
          features: [uploads, outputs, downloads]
      runs-on: ubuntu-latest

      steps:
        - name: Checkout code
          uses: actions/checkout@v2  # Include the checkout step
        
        - name: running
          run: echo "running job with ${{ matrix.features }}"

        - name: Deploy feature step
          uses: ./github/workflows/terraform-deploy.yml@main
          with:
            working-directory: ${{ inputs.working-directory }}
            stage: ${{ inputs.stage }}
            account: ${{ inputs.account }}
            region: ${{ inputs.region }}
            feature: ${{ matrix.features }}
